commandes:
    resource: "@CommandesBundle/Controller/"
    type:     annotation
    prefix:   /

ds_base:
    resource: "@DSBaseBundle/Controller/"
    type:     annotation
    prefix:   /

ds_account:
    resource: "@DSAccountBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
